language: php

sudo: false

notifications:
  email: false

addons:
  firefox: "47.0.1"
  postgresql: "9.3"
  #apt: #can be omitted because mustache is not in use
  #  packages:
  #    - oracle-java8-installer
  #    - oracle-java8-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 5.6
 #- 7.0
 #- 7.1

env:
  - MOODLE_BRANCH=MOODLE_31_STABLE DB=pgsql
  #- MOODLE_BRANCH=MOODLE_31_STABLE DB=mysqli
  #- MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql

matrix:
  include:
    - php: 7.1
      env: MOODLE_BRANCH=master DB=pgsql
#    - php: 7.1
#      env: MOODLE_BRANCH=master DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - echo "upload_max_filesize=20M\npost_max_size=20M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - nvm install node
  - cd ../..
  - if [ $MOODLE_BRANCH == 'MOODLE_31_STABLE' ]; then MOODLE_PLUGIN_CI_VERSION=1; else MOODLE_PLUGIN_CI_VERSION=2; fi
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^$MOODLE_PLUGIN_CI_VERSION
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - if [ $MOODLE_PLUGIN_CI_VERSION == '2' ]; then moodle-plugin-ci validate; fi
  - if [ $MOODLE_PLUGIN_CI_VERSION == '2' ]; then moodle-plugin-ci savepoints; fi
  #- if [ $MOODLE_PLUGIN_CI_VERSION == '2' ]; then moodle-plugin-ci; fi mustache #currently no mustache relevant files, so we can also save the oracle packages
  - if [ $MOODLE_PLUGIN_CI_VERSION == '2' ]; then moodle-plugin-ci grunt; fi
  - if [ $MOODLE_PLUGIN_CI_VERSION == '1' ]; then moodle-plugin-ci csslint; fi
  - if [ $MOODLE_PLUGIN_CI_VERSION == '1' ]; then moodle-plugin-ci shifter; fi
  - if [ $MOODLE_PLUGIN_CI_VERSION == '1' ]; then moodle-plugin-ci jshint; fi
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat